version: 2

models:
  - name: 01_merging
    description: "Sales joined to products with cleaned purchase_price and basic margin math."
    config:
       materialized: view
    columns:
      - name: products_id
        description: "Product id from product table (post-join)."
        tests: [not_null]

      - name: date_date
        tests: [not_null]

      - name: orders_id
        tests: [not_null]

      - name: pdt_id
        description: "Product id from sales table prior to join."
        tests:
          - not_null
          - relationships:
              to: ref('stg_gz_raw_data__raw_gz_product')
              field: products_id

      - name: revenue
        tests: [not_null]

      - name: quantity
        tests: [not_null]

      - name: purchase_price
        description: "Parsed numeric price from purchse_price."
        tests:
          - not_null
          # - dbt_expectations.expect_column_values_to_be_between:
          #     min_value: 0

      - name: purchase_cost
        description: "quantity * purchase_price (rounded 2)."

      - name: margin
        description: "revenue - purchase_cost (rounded 2)."

  - name: 02_merge_table
    description: "Copy of 01_merging for class; materialized as a table."
    #config:
    #  materialized: table

    columns:
      - name: date_date
      - name: pdt_id
      - name: products_id
      - name: orders_id
      - name: revenue
      - name: quantity
      - name: purchase_price
      - name: purchase_cost
      - name: shipping_cost
      - name: margin
      - name: margin_net